---
title: "USP 634: Data Analysis I Spring 2017 Syllabus"
#date: "4/4/2017"
output: html_document
---

## Course Website
https://usp634.github.io

## Room and Times: 
- **Lecture** 
     URBN 220, Tuesdays 4:00 - 6:30pm
- **Computer Lab**: 
     URBN 225, Tuesdays 6:40 - 7:30pm
- **Instructors**: 
     - Professor Liming Wang (lmwang@pdx.edu)
     - Office: Urban Center 350D
     - Office Hours: Tuesdays 3:00-4:00pm or by appointment
- **Lab Instructor/Teaching Assistant**: 
     - Jamaal Green (jamgreen@pdx.edu); by appointment.


## Synopsis
This course is designed to give students the necessary skills to analyze data for their research projects. Together with the second course, USP 654 Data Analysis II in the fall, the sequence will provide a thorough and reasonably comprehensive introduction to understanding, critically evaluating, conducting, and writing about analyses for most studies in social science-related disciplines. This course covers descriptive statistics, probability and distributions, hypothesis testing, association, and simple regression analysis. USP 654 Data Analysis II will cover regression analysis in more depth.
Prerequisite: College-level algebra, introductory probability and statistics and an understanding of research designs. The most critical elements of these materials will be reviewed in class. I can provide optional readings that will help provide additional review if you need it.

## Format

Classes will be a combination of lectures, discussion and computer labs.  Students are expected to read assigned readings before class and to participate in class discussions. Homework assignments will be given and analysis of these assignments will be the basis for some class discussion during the class following their due date, so it is essential to complete assignments on time. 

## Software: 

The assignments for this course will use the R statistical software (or your choice of other stats software, such as SAS, SPSS, or Stata). The lab instructions will use R. The software is installed on the lab computers across the campus. R is free and available for download at http://cran.r-project.org. We will use a RStudio (https://www.rstudio.com/) as our main interface to R. Labs will be offered weekly to assist in using R to complete the assignments and R examples will be used during regular sessions. Jamaal and I can provide additional assistance to with the software. If you plan to use other software, we will provide as much assistance as we can.

## Textbook and Readings: 

The recommended textbook for the course is 

- [Diez, D.M., Barr, C.D. and Çetinkaya-Rundel, M., 2015. OpenIntro Statistics: 3rd ed. CreateSpace Independent Publishing Platform, Lexington, KY.](https://www.openintro.org/stat/textbook.php)

Optional textbooks are:

1.	[Urdan, T.C., 2010. Statistics in Plain English, 3rd ed. Routledge, New York.](https://www.amazon.com/Statistics-Plain-English-Third-Timothy/dp/041587291X)
2.	[Myers, J.L., Well, A.D., and Lorch, R.F.,Jr., 2010. Research Design and Statistical Analysis: 3rd Edition. Mahwah, NJ: Erlbaum.](https://www.amazon.com/Research-Design-Statistical-Analysis-Third/dp/0805864318)
3.	[Gonick, L. and Smith, W., 1993. The Cartoon Guide to Statistics, 1st Edition. Collins Reference.](https://www.amazon.com/Cartoon-Guide-Statistics-Larry-Gonick/dp/0062731025)

There will also be supplemental readings that will be available for download from the course website.

## Grading: 

The course requirements include assigned readings, four assignments, attendance and class participation, and a research paper.

- **Assignments (60%)**: 
    Four homework assignments that involve completing analytical exercises designed to build skills in statistical analysis and to reinforce concepts discussed in the class lectures. Clarity in writing and presentation will be taken into account in grading. Students may collaborate on the approach to and analysis of homework assignments but are expected to prepare and present results and interpretations independently.
    
- **General Attendance and Class Participation (10%)**: 
    The class participation section of the grade does not merely measure attendance in class, but also reflects the student’s understanding of the subject matter, as reflected through insightful questions and discussion in class. There will be occasional in-class quizzes.
    
- **Research Project (30%)**: 
    In this class project, you will explore a topic of your choosing in depth, applying statistical methods covered in this class (and beyond) for your data analysis. Ideally, you would build upon work you have already done for other courses, such as USP 630 Research Design, USP 532 Data Collection. The paper must include original data analysis. This most likely will be analysis of secondary data. If you want to collect your own quantitative data, it may be possible, but will take more planning and work. Check with me first.
    Details:
    - 20-25 pages, double-spaced, not including figures, tables and references;
    - Initial proposal due on April 18th. It should include a brief description of the topic, a list of key references (including academic literature), specific research question(s) and hypotheses, and the data source(s) you plan to use;
    - Project updates due on May 16th. This should include a draft of the introduction/background sections, a brief literature review, the methodology and description and descriptive statistics of your data;
    - Project presentation on June 6th and 13th (tentative);
    - Final paper due Thursday June 15th.
    
    The best papers (high A grade) will be worthy of submission to an academic journal. Use empirical journal articles as a model to follow in terms of format, style, etc.
    
    You must cite all of your sources in your work. Please review this web site about citations: http://library.pdx.edu/citing_sources.html
    
    Late assignments will be marked down – one-third of a grade per day late. “One-third of a grade” is, for example, from A to A-, B+ to B, etc. (or 3.3 points using the 100 point scale). We generally do not allow students to turn things in late without assessing this penalty, except in unusual circumstances, e.g. medical emergencies. A request for such an extension must be made before the due date. Having too much work in other classes or at work/internship does not count. All students have those challenges.

## Schedule 

The table below shows by date lecture topics, computer labs, and readings, and dates that assignments will be handed out and due. Supplement readings will be posted on course website.

- Week 1 4/04
    - Topic: Course Overview; Stats and Research Design
    - Reading: 
    - Computer lab: Intro to R & RStudio
- Week 2 4/11
    - Topic: Descriptive Statistics 
    - Readings: Diez, Ch 1	
    - Computer lab
    - Deadline: HW1 assigned
- Week 3 4/18	
    - Topic: Probability and Distributions
    - Readings: Diez, Ch 2-3	
    - Computer lab
    - Deadline: Initial research proposal due
- Week 4 4/25
    - Topic: Foundation for Inferential Statistics
    - Computer lab	
    - Readings: Diez, Ch 4
    - Deadline: HW1 due; HW2 assigned
- Week 5 5/02	
    - Topic: Hypothesis Testing for Continuous Variable: t-tests
    - Computer lab	
    - Readings: Diez, Ch 5.1-4
- Week 6 5/09	
    - Topic: Hypothesis Testing for Categorical Variable: Chi-squared tests
    - Computer lab	
    - Readings: Diez, Ch 6	
    - Deadline: HW2 due; HW3 assigned
- Week 7 5/16	
    - Topic: Hypothesis Testing: ANOVA
    - Computer lab	
    - Readings: Diez, Ch 5.5	
    - Deadline: Paper update due
- Week 8 5/23	
    - Topic Association and Correlation
    - Readings: Diez, Ch 7.1
    - Computer lab	
    - Deadline: HW3 due; HW4 assigned
- Week 9 5/30	
    - Topic: Linear Regression
    - Readings: Diez, Ch 7.2-4
    - Computer lab
- Week 10 6/06	
    - Final project presentation
    - Deadline: HW4 due
- Finals Week	
    - Tue 6/13 Final project presentation (cont’d) (tentative date)
    -	Thursday 6/15 Final paper due
